config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :chats do
    resources :messages, only: [ :create ]
  end

  root "chats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages, dependent: :destroy

  accepts_nested_attributes_for :messages, allow_destroy: true

  # validates :title, presence: true

  broadcasts_to ->(chat) { "chats" }, inserts_by: :prepend

  scope :today, -> { where(created_at: Time.zone.now.all_day) }
  scope :yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :last_7_days, -> { where(created_at: 7.days.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :last_30_days, -> { where(created_at: 30.days.ago.beginning_of_day..Time.zone.now.end_of_day) }
end

app/models/message.rb
class Message < ApplicationRecord
  extend Enumerize
  include ChatsHelper

  belongs_to :chat
  has_one :setting, dependent: :destroy

  accepts_nested_attributes_for :setting, allow_destroy: true

  enumerize :deepseek_model_role, in: [ :user, :assistant, :function ]

  # validates :deepseek_model_role, :content, presence: true

  def self.role_choices
    deepseek_model_role.values.map { |k| [ k.humanize.downcase, k ] }
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
  extend Enumerize
  include ChatsHelper

  belongs_to :message

  enumerize :deepseek_model_name, in: [ "deepseek-chat", "deepseek-reasoner" ]

  def self.model_choices
    deepseek_model_name.values.map { |k| [ k.humanize.downcase, k ] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :chat, only: %i[show edit update destroy]

  def index
    @chats = Chat.all
    @chat = Chat.new
    @message = @chat.messages.build
    @setting = @message.build_setting

    @chats_by_period = format_periods
  end

  def show
    @messages = @chat.messages.order(created_at: :asc)
    @new_chat = Chat.new
    @message = @new_chat.messages.build
    @setting = @message.build_setting

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("chat_frame", template: "chats/show")
      ]
      end
      format.html
    end
  end

  def new
    @chat = Chat.new
    @message = @chat.messages.build
    @setting = @message.build_setting

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("chat_frame", template: "chats/new")
      ]
      end
      format.html
    end
  end

  def edit; end

  def create
    @chat = Chat.new(chat_params)

    if @chat.valid?
      @chat.save
      message = @chat.messages.last

      response = DeepseekApi::DeepseekClient.new.call(message)

      if response["reasoning_content"].present?
        reasoning_content = Commonmarker.to_html(response["reasoning_content"], options: { parse: { smart: true } })
      end

      answer_content = Commonmarker.to_html(response["content"], options: { parse: { smart: true } })

      @chat.messages.last.update(content: message.content, result: answer_content, reasoning_content: reasoning_content)

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("chat_frame", template: "chats/show")
          ]
        end
        format.html { redirect_to chat_path(@chat), status: :see_other }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if chat.update(title: chat_params[:title])
      redirect_to chats_path, status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    chat.destroy
    redirect_to chats_path
  end

  private

  def chat_params
    params.require(:chat).permit(:title,
      messages_attributes: [ :id, :deepseek_model_role, :content, :result, :reasoning_content, :add_assistant, :assistant_prompt, :_destroy,
      setting_attributes: [ :id, :deepseek_model_name, :temperature, :max_tokens, :top_p, :stream, :_destroy ] ])
  end

  def chat
    @chat ||= Chat.find(params[:id])
  end

  def format_periods
    periods = {
      today: Chat.today.order(created_at: :desc),
      yesterday: Chat.yesterday.order(created_at: :desc),
      last_7_days: Chat.last_7_days - Chat.today - Chat.yesterday,
      last_30_days: Chat.last_30_days - Chat.last_7_days
    }

    periods.delete_if { |_, tasks| tasks.empty? }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_chat, only: [ :create ]

  def create
    @message = @chat.messages.build(message_params)

    if @message.valid?
      @message.save
      content =  @message.content
      previous_messages = @chat.messages.where("id < ?", @chat.messages.maximum(:id))
      messages_data = previous_messages.pluck(:deepseek_model_role, :content, :result).flat_map do |role, content, result|
        [
          { role: role, content: content },
          { role: "assistant", content: result }
        ]
      end

      response = DeepseekApi::DeepseekClient.new.call(@message, messages_data)

      if response["reasoning_content"].present?
        reasoning_content = Commonmarker.to_html(response["reasoning_content"], options: { parse: { smart: true } })
      end

      answer_content = Commonmarker.to_html(response["content"], options: { parse: { smart: true } })

      @message.update(content: content, result: answer_content, reasoning_content: reasoning_content)

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace("chat_frame", template: "chats/show")
          ]
        end
        format.html { redirect_to chat_path(@chat), status: :see_other }
      end
    else
      render "chats/show", status: :unprocessable_entity
    end
  end

  private

  def set_chat
    @chat = Chat.find(params[:chat_id])
  end

  def message_params
    params.require(:message).permit(:chat_id, :deepseek_model_role, :content, :result, :reasoning_content,
                                    :add_assistant, :assistant_prompt,
            setting_attributes: [ :id, :deepseek_model_name, :temperature, :max_tokens, :top_p, :stream, :_destroy ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
  def format_period_name(period)
    case period
    when :today then "Today"
    when :yesterday then "Yesterday"
    when :last_7_days then "7 Days"
    when :last_30_days then "30 Days"
    end
  end
end

app/views/chats/_chat.html.erb
<li class="col-auto chat-modal list-unstyled"
    data-modal-target="item"
    id="<%= dom_id(chat) %>"
    data-controller="tooltip"
    data-bs-toggle="tooltip"
    data-bs-placement="right"
    title="<%= chat.messages.first&.content %>">
  <%= link_to truncate((chat.title || chat.messages.first&.content), omission: ''), chat_path(chat),
                                                                  data: { turbo_frame: "chat_frame", },
                                                                  class: "text-decoration-none text-reset" %>
  <button type="button" data-action="modal#toggleMenu" class="btn options-btn">
    <%= image_tag "three-dots-16.png" %>
  </button>
  <div class="options-modal hidden rounded" data-modal-target="menu">
    <div class="d-flex flex-column justify-content-center align-items-center gap-2">
      <%= turbo_frame_tag "rename_frame" do %>
        <%= link_to "✏️ Rename", edit_chat_path(chat), class: "btn btn-secondary btn-sm btn-custom" %>
      <% end %>
      <%= link_to "🗑️ Delete", chat_path(chat),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                  class: "btn btn-danger btn-sm btn-custom" %>
    </div>
  </div>
</li>

app/views/chats/_chat_list.html.erb
<ul class="chats overflow-auto p-0" data-controller="modal">
  <% chats.each do |chat| %>
    <%= render "chats/chat", chat: chat %>
  <% end %>
</ul>

app/views/chats/_common_form_setting.html.erb
<%= f.fields_for :setting_attributes do |setting_form| %>
  <div class="form-group row">
    <%= setting_form.label :model_name, class: "col-sm-4 col-form-label" %>
    <div class="col-sm-6">
      <%= setting_form.select :deepseek_model_name, Setting.model_choices, {}, value: "deepseek-chat", class: "form-select mb-3",
                    data: { action: "change->disable-fields#toggle", disable_fields_target: "modelSelect" }  %>
    </div>
  </div>
  <div class="form-group row">
    <%= setting_form.label :top_p, "Top_p (0-1):", class: "col-sm-4 col-form-label" %>
    <div class="col-sm-3">
      <%= setting_form.number_field :top_p, value: 0.9, step: 0.1, min: 0, max: 1, class: "form-control mb-3",
                          data: { disable_fields_target: "topField" } %>
    </div>
  </div>
  <div class="form-group row">
    <%= setting_form.label :temperature, "Temperature (0-1):", class: "col-sm-4 col-form-label" %>
    <div class="col-sm-3">
      <%= setting_form.number_field :temperature, value: 0.7, step: 0.1, min: 0, max: 1.5, class: "form-control mb-3",
                          data: { disable_fields_target: "temperatureField" } %>
    </div>
  </div>
  <div class="form-group row">
    <%= setting_form.label :max_tokens, "Max Tokens:", class: "col-sm-4 col-form-label" %>
    <div class="col-sm-3">
      <%= setting_form.number_field :max_tokens, value: 4000, min: 1, max: 8000, class: "form-control mb-3" %>
    </div>
  </div>
  <div class="form-group row">
    <%= setting_form.label :top_p, "Top_p (0-1):", class: "col-sm-4 col-form-label" %>
    <div class="col-sm-3">
      <%= setting_form.number_field :top_p, value: 0.9, step: 0.1, min: 0, max: 1, class: "form-control mb-3", data: { disable_fields_target: "topField" } %>
    </div>
  </div>
  <div class="form-group row">
    <%= setting_form.label :stream, class: "col-sm-4 col-form-label" %>
    <div class="col-sm-3">
      <%= setting_form.select :stream, options_for_select([['no', false], ['yes', true]]), {}, class: "form-select mb-3" %>
    </div>
  </div>
<% end %>

app/views/chats/_form.html.erb
<div class="p-5 rounded-5 custom-input bg-light mb-5">
  <%= form_with(model: @chat, local: true) do |f| %>
    <%= f.fields_for :messages do |message_form| %>
      <div class="form-group" data-controller="autosize-textarea">
        <%= message_form.text_area :content, rows: 2, required: true, placeholder: "Message DeepSeek",
                                    class: "form-control",
                                    data: { "autosize-textarea-target": "textarea",
                                    action: "input->autosize-textarea#adjustHeight" }
        %>
      </div>
      <div class="accordion accordion-flush mt-3 rounded-5" id="accordionFlushExample">
        <div class="accordion-item mb-2">
          <h2 class="accordion-header" id="flush-headingOne">
            <button class="accordion-button collapsed"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseOne"
                    aria-expanded="false"
                    aria-controls="flush-collapseOne">
              Settings
            </button>
          </h2>
          <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body" data-controller="disable-fields select-assistant">
              <div class="form-group row">
                <%= message_form.label :role, class: "col-sm-4 col-form-label" %>
                <div class="col-sm-6">
                  <%= message_form.select :deepseek_model_role, Message.role_choices, {}, value: "user", class: "form-select mb-3" %>
                </div>
              </div>
              <div class="form-group row">
                <%= message_form.label :add_assistant_prompt, class: "col-sm-4 col-form-label" %>
                <div class="col-sm-3">
                  <%= message_form.select :add_assistant, [['no', false], ['yes', true]], {},
                                          data: { action: "select-assistant#toggle", select_assistant_target: "selector", value: false },
                                          class: "form-select mb-3" %>
                </div>
              </div>
              <div class="form-group row hidden" data-select-assistant-target="field" data-controller="autosize-textarea">
                <%= message_form.label :assistant_prompt, class: "col-sm-4 col-form-label" %>
                <div class="col-sm-6">
                  <%= message_form.text_area :assistant_prompt, rows: 2, required: true,
                                    value: "You are a helpful AI assistant who responds politely and briefly. And at the end, wish a good day.",
                                    class: "form-control mb-3",
                                    data: { "autosize-textarea-target": "textarea",
                                    action: "input->autosize-textarea#adjustHeight" } %>
                </div>
              </div>
              <%= render "chats/common_form_setting", f: message_form %>
            </div>
          </div>
        </div>
      </div>
      <div class="d-flex flex-column">
        <%= button_tag(type: 'submit', class: 'btn btn-secondary mt-2') do %>
          <i class="bi bi-send"></i>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chats/_rename_title.html.erb
<%= turbo_frame_tag "rename_frame" do %>
  <%= form_with(model: @chat, local: true) do |form| %>
    <div>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="d-flex flex-column">
      <%= button_tag(type: 'submit', data: { action:"modal#toggleMenu" }, class: 'btn btn-secondary mt-2') do %>
        <i class="bi bi-send"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/edit.html.erb
<%= render 'rename_title' %>

app/views/chats/index.html.erb
<div class="container-fluid">
  <div class="row no-gutters">
    <div class="col-auto left-column">
      <!-- Содержимое левой колонки -->
      <div class="p-3">
        <h3 class="mt-3 custom-title"><b>deepseek's answers</b></h3>
        <%= link_to "New chat", new_chat_path(@chat), data: { turbo_frame: "chat_frame" }, class: "btn btn-secondary mt-4 mb-4" %></p>
          <% if @chats_by_period.present? %>
            <% @chats_by_period.each do |period, chats| %>
              <%= turbo_stream_from "chats" %>
              <h5><%= format_period_name(period) %></h5>
              <div id="chats">
                <%= render "chats/chat_list", chats: chats %>
              </div>
            <% end %>
          <% else %>
            <p>No chats available</p>
          <% end %>
      </div>
    </div>
    <div class="col right-column">
      <%= turbo_frame_tag "chat_frame" do %>
        <%= render template: "chats/new", layout: false %>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/new.html.erb
<%= turbo_frame_tag "chat_frame" do %>
  <div class="d-flex flex-column justify-content-center align-items-center mt-5">
    <div class="row align-items-center p-3 mb-3">
      <div class="col-auto">
        <%= image_tag "deepseek.png", alt: 'Описание изображения', size: "47x47", class: 'img-fluid' %>
      </div>
      <div class="col-auto">
        <h3>Hi, I'm DeepSeek.</h3>
      </div>
    </div>
    <%= render "form" %>
  </div>
<% end %>

app/views/chats/show.html.erb
<%= turbo_frame_tag "chat_frame" do %>
  <div class="container my-5">
    <div class="row justify-content-center">
      <% if defined?(@chat) %>
        <h4 class="card-text text-center  mt-2 mb-3 ">
          <%= @chat.title %>
        </h4>
        <% @chat.messages.each do |message| %>
          <div class="col-md-7">
            <!-- Блок с вопросом -->
            <div class="card mb-4">
              <div class="card-header bg-blue-200">
                Question
              </div>
              <div class="card-body">
                <div class="card-text">
                  <%= message.content %>
                </div>
              </div>
            </div>
            <!-- Блок рассуждения -->
            <% if message.reasoning_content.present?  %>
              <div class="card mb-5">
                <div class="card-header bg-orange-200">
                  Reasoning
                </div>
                <div class="card-body">
                  <p class="card-text text-muted">
                    <%= sanitize message.reasoning_content %>
                  </p>
                </div>
              </div>
            <% end %>
            <!-- Блок с ответом -->
            <div class="card mb-5">
              <div class="card-header bg-green-200">
                Answer
              </div>
              <div class="card-body">
                <p class="card-text">
                  <%= sanitize message.result %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <h4 class="card-text text-center  mt-2 mb-3 ">No chats</h4>
      <% end %>
      <div class="md-5 text-center">
        <%= link_to "New chat", new_chat_path(@new_chat), data: { turbo_frame: "chat_frame" }, class: "btn btn-secondary mb-5" %></p>
      </div>
      <%= render 'messages/form', chat: @chat %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Deepseek Chat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="p-5 rounded-5 custom-input bg-light mb-5">
  <%= form_with model: [chat, Message.new], local: true do |f| %>
    <div class="form-group" data-controller="autosize-textarea">
      <%= f.text_area :content, rows: 2, required: true, placeholder: "Message DeepSeek",
                                  class: "form-control",
                                  data: { "autosize-textarea-target": "textarea",
                                  action: "input->autosize-textarea#adjustHeight" }
      %>
    </div>
    <div class="accordion accordion-flush mt-3 rounded-5" id="accordionFlushExample">
      <div class="accordion-item mb-2">
        <h2 class="accordion-header" id="flush-headingOne">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
            Settings
          </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body" data-controller="disable-fields">
            <div class="form-group row">
              <%= f.label :role, class: "col-sm-4 col-form-label" %>
              <div class="col-sm-6">
                <%= f.text_field :deepseek_model_role, value: "user", class: "form-control mb-3", readonly: true %>
              </div>
            </div>
            <%= render "chats/common_form_setting", f: f %>
          </div>
        </div>
      </div>
    </div>
    <div class="d-flex flex-column">
      <%= button_tag(type: 'submit', class: 'btn btn-secondary mt-2') do %>
        <i class="bi bi-send"></i>
      <% end %>
    </div>
  <% end %>
</div>